In [0]:
import numpy as np

In [18]:
a = np.array([[4.0,-2.0, 1.0], [-2.0, 4.0, -2.0], [1.0, -2.0, 4.0]])
nx, ny = a.shape
print(a)

[[ 4. -2.  1.]
 [-2.  4. -2.]
 [ 1. -2.  4.]]


In [0]:
b = np.array([11.0,-16.0,17.0])

In [0]:
# Ly = b 
def forwardSubstitution(l, b):
  n = len(b)
  x = np.zeros([n])
  for i in range(0, n):
    x[i] = b[i] - np.dot(u[i, 0:i], x[i, 0:i]);
  return x

**Back Solution Ux = y (then)**
```
u11 u12 u13 | x1 = y1
0   u22 u23 | x2 = y2
0   0   u33 | x3 = y3
(...)
xn = yn/unn
xn-1 = (y(n-1)-xn*u(n-1n)/u(n-1n-1) 
```

In [0]:
# Ux = b
# return x is array size n

# u11 u12 u13 = b1
# 
def backSubstituion(u, b): 
  n = len(b)
  for i in range(n-1, -1, -1):
    b[i] = (b[i] - np.dot(u[i,i+1:n], b[i+1:n]))/u[i, i];
  return b

In [0]:
# U fatoring for Ux = y 
#return [A|b] (matriz aumentada)
def Ufatoring(u, y):
  n = len(y)

  for k in range(0, n-1):
    for i in range(k+1, n):
      m = 0.0;
      if(u[i, k]!=0):
        m = u[i, k]/u[k, k]
        u[i, k+1:n] -= m*u[k, k+1:n];
        y[i] -= m*y[k]; 

  print("U:\n", u)
  print("y:\n", y)
  return [u, y]

In [0]:
# Gaus Elination
# return Ax = b
def gausElimination(a, b):
  u, y = Ufatoring(a, b)
  x = backSubstituion(u, y)
  return x

In [24]:
print("Solution x is: ")
print(gausElimination(np.copy(a), np.copy(b)))

Solution x is: 
U:
 [[ 4.  -2.   1. ]
 [-2.   3.  -1.5]
 [ 1.  -1.5  3. ]]
y:
 [ 11.  -10.5   9. ]
[ 1. -2.  3.]
