In [0]:
import numpy as np

**Foward Solution Ly = b (then)**, y = Ux
```
l11 0   0   | y1  = b1
l21 l22 0   | y2  = b2
l31 l32 l33 | y3  = b3
(...)

y1 = b1 / l11
y2 = (b2 - l21*y1 ) / l22
y3 = (b3 - l31*y1 - l32*y2) / l33

for i = 0..n-1
  yi = (bi - dot(matrix[i, 0:i], y[i, 0:i]))
```

In [0]:
# Ly = b 
def forwardSubstitution(l, b):
  n = len(l)
  for i in range(1, n):
    b[i] = b[i] - np.dot(l[i, 0:i], b[0:i]);
  return b

**Back Solution Ux = y (then)**
```
u11 u12 u13 | x1 = y1
0   u22 u23 | x2 = y2
0   0   u33 | x3 = y3
(...)
xn = yn/unn
xn-1 = (y(n-1)-xn*u(n-1n)/u(n-1n-1) 
```

In [0]:
# Ux = b
# return x is array size n

# u11 u12 u13 = b1
# 
def backSubstituion(u, b): 
  n = len(b)
  for i in range(n-1, -1, -1):
    b[i] = (b[i] - np.dot(u[i,i+1:n], b[i+1:n]))/u[i, i];
  return b

** A = LU **
```
A = [L\U]
A = u11 u12 u13
    l21 u22 u23
    l31 l32 u33
```

In [0]:
# LU fatoring for Ux = y 
#return [L\U|b] (matriz aumentada)
def LUfatoring(a):
  n = len(a)

  for k in range(0, n-1):
    for i in range(k+1, n):
      if(a[i, k]!=0):
        m = a[i, k]/a[k, k]
        a[i, k+1:n] -= m*a[k, k+1:n];
        a[i, k] = m;

  print("A=LU:\n", a)
  return a

In [0]:
def solveLU(a, b):
  a = LUfatoring(a)
  y = forwardSubstitution(a, b);
  print(y)
  x = backSubstituion(a, y); 
  return x

Testing...

In [70]:
ok = True;
a = np.array([[4.0,-2.0, 1.0], [-2.0, 4.0, -2.0], [1.0, -2.0, 4.0]])
if(a.shape[0] != a.shape[1]):
  print("You should use nxn quadratic matrix, go back!")
  ok = False;
else:
  n  = a.shape[0]
print(a)

[[ 4. -2.  1.]
 [-2.  4. -2.]
 [ 1. -2.  4.]]


In [71]:
b = np.array([11.0,-16.0,17.0])
if(b.shape[0]==n):
  ok = True
else:
  ok = False
print(b)

[ 11. -16.  17.]


In [72]:
print("Solution x is: ")
print(solveLU(a, b))

Solution x is: 
A=LU:
 [[ 4.   -2.    1.  ]
 [-0.5   3.   -1.5 ]
 [ 0.25 -0.5   3.  ]]
[ 11.  -10.5   9. ]
[ 1. -2.  3.]
