In [0]:
import numpy as np

** Choleski's method **
```
A is such as A = A^t (A is equal yoir transverse mode)
A is positive defined
L is the lower trianguler matrix of A:

 1   0  0
l21  1  0
l31 l32 1

and L^t is transverse of L.

the,
A = L (L^t),
```

In [0]:
def transverse(a):
  n = len(a)
  for i in range(0, n):
    b = np.copy(a[i, i:n])
    a[i, i:n] = np.copy(a[i:n, i])
    a[i:n, i] = np.copy(b)
  return a

testing...

In [78]:
ok = True;
# a = np.array([[4.0,-2.0, 1.0], [-2.0, 4.0, -2.0], [1.0, -2.0, 4.0]])
a = np.array([[3.0,-1.0, -1.0], [-1.0, 3.0, -1.0], [-1.0, -1.0, 3.0]])

c = transverse(np.copy(a))
if( (a.shape[0] != a.shape[1])):
  print("You should use nxn quadratic matrix, go back!")
  ok = False;
else:
  n  = a.shape[0]
  print("Choleski's Decomposition")
print(a == c)

Choleski's Decomposition
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [0]:
def choleskis(a):
  n = len(a)
  for i in range(0, n):
    try:
      a[i, i] = np.sqrt(a[i, i]-np.dot(a[i, 0:i], a[i, 0:i]))
    except ValueError:
      error.err('Not a define posit]ive Matrix')  
    for k in range(i+1, n):
      a[k,i] = (a[k,i] - np.dot(a[k, 0:i], a[i, 0:i]))/a[i,i]
  for k in range(1, n):
    a[0:k, k] = 0.0
  return a

In [85]:
l = choleskis(np.copy(a));
c = transverse(np.copy(l));

print(a)
print(l)
print(c)
print(l.dot(c))

[[ 3. -1. -1.]
 [-1.  3. -1.]
 [-1. -1.  3.]]
[[ 1.73205081  0.          0.        ]
 [-0.57735027  1.63299316  0.        ]
 [-0.57735027 -0.81649658  1.41421356]]
[[ 1.73205081 -0.57735027 -0.57735027]
 [ 0.          1.63299316 -0.81649658]
 [ 0.          0.          1.41421356]]
[[ 3. -1. -1.]
 [-1.  3. -1.]
 [-1. -1.  3.]]
